# Generated by Django 2.2 on 2020-04-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用户名', max_length=10)),
                ('phone', models.CharField(help_text='手机号', max_length=11)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, help_text='性别')),
                ('password', models.CharField(help_text='密码', max_length=10)),
            ],
        ),
    ]
